all: rmats-turbo PAIRADISE DARTS
	ls -lh

rmats-turbo:
	git clone https://github.com/Xinglab/rmats-turbo.git

PAIRADISE:
	git clone https://github.com/Xinglab/PAIRADISE.git

DARTS:
	git clone https://github.com/Xinglab/DARTS.git
