[workspace]
authors = ["HU Xuesong <87519979+huxs001@users.noreply.github.com>"]
channels = ["conda-forge", "bioconda"]
name = "gromacs"
platforms = ["osx-arm64", { name = "gpu-linux-64", platform = "linux-64", cuda = "12.4", glibc = "2.17" }, { name = "centos75", platform = "linux-64", glibc = "2.17", linux = "3.10" }]
version = "0.1.0"

[tasks]

[tasks._d_plumed]
cmd = "mkdir -p pkg && curl -L -C - -o pkg/plumed-src-2.10.1.tgz https://github.com/plumed/plumed2/releases/download/v2.10.1/plumed-src-2.10.1.tgz"
outputs = ["pkg/plumed-src-2.10.1.tgz"]

[tasks._d_gromacs]
cmd = "mkdir -p pkg && curl -L -C - -o pkg/gromacs-2023.5.tar.gz https://ftp.gromacs.org/gromacs/gromacs-2023.5.tar.gz"
outputs = ["pkg/gromacs-2023.5.tar.gz"]

[tasks._mk_plumed]
depends-on = ["_d_plumed"]
cmd = "tar -xf pkg/plumed-src-2.10.1.tgz && cd plumed-2.10.1 && ./configure --prefix=\"$(pwd)/../local\" && make install && rm src/include/plumed"
outputs = ["local/bin/plumed", "local/bin/plumed-patch"]

[tasks._p_gromacs]
depends-on = ["_d_gromacs", "_mk_plumed"] # 必须确保 plumed 先编译完成并生成了 patch 工具
cmd = "tar -xf pkg/gromacs-2023.5.tar.gz && cd gromacs-2023.5 && plumed-patch -e gromacs-2023.5 -p"
outputs = ["gromacs-2023.5/src/gromacs/mdrun/runner.cpp.preplumed"]

[tasks._mk_gromacs]
depends-on = ["_p_gromacs", "_mk_plumed"]
cmd = "mkdir -p gromacs-2023.5/build && cd gromacs-2023.5/build && cmake .. $DGROMACS0 $DGROMACS1 $DGROMACS2 && make -j && make install"
outputs = ["local/bin/gmx_mpi", "gromacs-2023.5/build/bin/gmx_mpi"]

[tasks.down]
depends-on = ["_d_plumed", "_d_gromacs"]

[tasks.build]
depends-on = ["_mk_plumed", "_mk_gromacs"]

[activation]
env = {
    PATH = "$PIXI_PROJECT_ROOT/local/bin:$PATH",
    DGROMACS0 = "-DGMX_USE_PLUMED=ON -DGMX_THREAD_MPI=OFF -DGMX_MPI=ON -DCMAKE_INSTALL_PREFIX=$PIXI_PROJECT_ROOT/local"
}
scripts = ["local/bin/GMXRC.bash"]

[target.osx-arm64.activation.env]
DGROMACS1 = "-DGMX_GPU=OpenCL -DGMX_DOUBLE=OFF"
DGROMACS2 = ""
FI_PROVIDER = "tcp"

[target.linux-64.activation.env]
LD_LIBRARY_PATH = "$PIXI_PROJECT_ROOT/local/lib:$LD_LIBRARY_PATH"
DGROMACS1 = "-DGMX_GPU=CUDA"
DGROMACS2 = """
-DCMAKE_INSTALL_LIBDIR=lib \
-DCUDA_NVCC_EXECUTABLE=$PIXI_PROJECT_ROOT/.pixi/envs/default/bin/nvcc \
-DCMAKE_CUDA_COMPILER=$PIXI_PROJECT_ROOT/.pixi/envs/default/bin/nvcc
"""
GMX_FORCE_GPU_AWARE_MPI = "1"

[dependencies]
compilers = ">=1.10.0,<3"
_openmp_mutex = ">=4.5,<5"
cmake = ">=3.18.4,<4"
make = ">=4.4.1,<5"
patch = ">=2.8,<3"
pip = ">=26.2.1,<27"
setuptools = ">=84.0.0,<85"
cython = ">=3.3.0,<4"
pkg-config = ">=0.29.2,<0.30"
fftw = { build = "mpi_*", version = ">=3.3,<4" }
libhwloc = ">=2.12.2,<3"
pocl = ">=7.1,<8"

[target.osx-arm64.dependencies]
mpich = ">=5.0.0,<6"
khronos-opencl-icd-loader = ">=2024.10.24,<2025"
ocl_icd_wrapper_apple = ">=1.0.0,<2"

[target.linux-64.dependencies]
openmpi = ">=5.0.8,<6"
cuda-compiler = ">=12.4,<14"
cuda-libraries = ">=12.4,<14"
cuda-libraries-dev = ">=12.4,<14"
cuda-nvml-dev = ">=12.4,<14"
ocl-icd = ">=2.3.4,<3"
