[workspace]
authors = ["HU Xuesong <87519979+huxs001@users.noreply.github.com>"]
channels = ["conda-forge", "bioconda"]
name = "gromacs"
platforms = ["osx-arm64", { name = "gpu-linux-64", platform = "linux-64", cuda = "12.4", glibc = "2.17" }, { name = "centos75", platform = "linux-64", glibc = "2.17", linux = "3.10" }, "linux-64"]
version = "0.1.0"

[tasks]

[tasks._d_plumed]
cmd = """
    mkdir -p pkg \
    && curl -L -C - -o pkg/plumed-src-2.10.1.tgz \
        https://github.com/plumed/plumed2/releases/download/v2.10.1/plumed-src-2.10.1.tgz
"""
outputs = ["pkg/plumed-src-2.10.1.tgz"]

[tasks._d_gromacs]
args = [{ arg = "version", default = "2023.5", choices = ["2023.5", "2024.6", "2025.5", "2026.3"] }]
cmd = """
    mkdir -p pkg \
    && curl -L -C - -o pkg/gromacs-{{ version }}.tar.gz \
        https://ftp.gromacs.org/gromacs/gromacs-{{ version }}.tar.gz
"""
outputs = ["pkg/gromacs-{{ version }}.tar.gz"]

[tasks._mk_plumed]
depends-on = ["_d_plumed"]
cmd = """
    test -f local/bin/plumed-patch || ( \
        tar -xf pkg/plumed-src-2.10.1.tgz \
        && cd plumed-2.10.1 \
        && ./configure --prefix=\"$(pwd)/../local\" \
        && make install \
        && rm src/include/plumed \
    )
"""
outputs = ["local/bin/plumed", "local/bin/plumed-patch"]

[tasks._p_gromacs]
args = [{ arg = "version", default = "2023.5", choices = ["2023.5", "2024.6", "2025.5", "2026.3"] }]
depends-on = [
    { task = "_d_gromacs", args = ["{{ version }}"] },
    "_mk_plumed",
] # 必须确保 plumed 先编译完成并生成了 patch 工具
cmd = """
    test -d gromacs-{{ version }} || tar -xf pkg/gromacs-{{ version }}.tar.gz \
    && cd gromacs-{{ version }} \
    && plumed-patch -e gromacs-{{ version }} -p
"""
outputs = ["gromacs-{{ version }}/src/gromacs/mdrun/runner.cpp.preplumed"]

[tasks._mk_gromacs]
args = [
    { arg = "version", default = "2023.5", choices = ["2023.5", "2024.6", "2025.5", "2026.3"] },
    { arg = "variant", default = "single", choices = ["single", "double", "ocl"] },
]
depends-on = [
    { task = "_p_gromacs", args = ["{{ version }}"] },
    "_mk_plumed",
]
cmd = """
    mkdir -p gromacs-{{ version }}/build_{{ variant }} \
    && cd gromacs-{{ version }}/build_{{ variant }} \
    && cmake --fresh .. \
        $DGROMACS_Common \
        -DGMX_DEFAULT_SUFFIX=OFF \
        $DGROMACS_GPU_Toolchain \
        {% if variant == "double" %}
        -DGMX_GPU=OFF -DGMX_DOUBLE=ON \
        -DGMX_BINARY_SUFFIX=${GMX_SUFFIX}_d \
        -DGMX_LIBS_SUFFIX=${GMX_SUFFIX}_d \
        {% elif variant == "ocl" %}
        -DGMX_GPU=OpenCL \
        -DGMX_BINARY_SUFFIX=$GMX_SUFFIX \
        -DGMX_LIBS_SUFFIX=$GMX_SUFFIX \
        {% else %}
        $DGROMACS_GPU \
        -DGMX_BINARY_SUFFIX=$GMX_SUFFIX \
        -DGMX_LIBS_SUFFIX=$GMX_SUFFIX \
        {% endif %}
        -DCMAKE_INSTALL_PREFIX=$PIXI_PROJECT_ROOT/local/{{ version }} \
    && make \
    && make install
"""
outputs = [
    "local/{{ version }}/bin/gmx{{ GMX_SUFFIX }}{% if variant == \"double\" %}_d{% endif %}",
    "gromacs-{{ version }}/build_{{ variant }}/bin/gmx{{ GMX_SUFFIX }}{% if variant == \"double\" %}_d{% endif %}",
]

[target.linux-64.tasks.mk_gromacs_ocl]
args = [{ arg = "version", default = "2023.5", choices = ["2023.5", "2024.6", "2025.5", "2026.3"] }]
depends-on = [{ task = "_mk_gromacs", args = ["{{ version }}", "ocl"] }]

[tasks.down]
args = [{ arg = "version", default = "2023.5", choices = ["2023.5", "2024.6", "2025.5", "2026.3"] }]
depends-on = [
    "_d_plumed",
    { task = "_d_gromacs", args = ["{{ version }}"] },
]

[tasks.build]
args = [{ arg = "version", default = "2023.5", choices = ["2023.5", "2024.6", "2025.5", "2026.3"] }]
depends-on = [
    "_mk_plumed",
    { task = "_mk_gromacs", args = ["{{ version }}", "single"] },
    { task = "_mk_gromacs", args = ["{{ version }}", "double"] },
]

[activation]
env = {
    PATH = "$PIXI_PROJECT_ROOT/local/bin:$PATH",
    DGROMACS_Common = "-DGMX_USE_PLUMED=ON -DGMX_THREAD_MPI=OFF -DGMX_MPI=ON -DGMX_HWLOC=ON",
    GMX_SUFFIX = "_mpi",
    CXXFLAGS = "-Wno-missing-include-dirs -Wno-deprecated-literal-operator -Wno-deprecated-declarations -Wno-switch-default"
}
scripts = ["local/bin/GMXRC.bash"]

[target.osx-arm64.activation.env]
MAKEFLAGS = "-j4"
DGROMACS_GPU = "-DGMX_GPU=OpenCL -DGMX_DOUBLE=OFF"
DGROMACS_GPU_Toolchain = """ \
-DOpenCL_INCLUDE_DIR=$CONDA_PREFIX/include \
-DOpenCL_LIBRARY=$CONDA_PREFIX/lib/libOpenCL.dylib \
"""
FI_PROVIDER = "tcp"

[target.linux-64.activation.env]
MAKEFLAGS = "-j8"
LD_LIBRARY_PATH = "$PIXI_PROJECT_ROOT/local/lib:$LD_LIBRARY_PATH"
DGROMACS_GPU = "-DGMX_GPU=CUDA"
DGROMACS_GPU_Toolchain = """ \
-DCMAKE_INSTALL_LIBDIR=lib \
-DCUDA_NVCC_EXECUTABLE=$CONDA_PREFIX/bin/nvcc \
-DCMAKE_CUDA_COMPILER=$CONDA_PREFIX/bin/nvcc \
"""
GMX_SUFFIX = "_mpi_ocl"
GMX_FORCE_GPU_AWARE_MPI = "1"

[dependencies]
compilers = ">=1.10.0,<3"
_openmp_mutex = ">=4.5,<5"
cmake = ">=3.18.4,<4"
make = ">=4.4.1,<5"
patch = ">=2.8,<3"
pip = ">=26.2.1,<27"
setuptools = ">=84.0.0,<85"
cython = ">=3.3.0,<4"
pkg-config = ">=0.29.2,<0.30"
fftw = ">=3.3,<4"
libhwloc = ">=2.12.2,<3"
pocl = ">=7.1,<8"

[feature.mpi-slurm]
channels = ["conda-forge/label/mpi-external"]
dependencies = { fftw = { build = "mpi_*" } }

[feature.mpi-slurm.target.linux-64]
activation.env = { USE_SLURM = "1" }
activation.scripts = [ "activate_mpi.sh" ]
dependencies = { openmpi = { version = ">=5.0.8,<6", build = "external_*" } }

[feature.mpi-slurm.target.osx-arm64.dependencies]
openmpi = ">=5.0.8,<6"

[feature.mpi-slurm.target.osx-arm64.activation.env]
GMX_SUFFIX = "_ompi"

[feature.mpi.target.linux-64.dependencies]
openmpi = ">=5.0.8,<6"
fftw = { build = "mpi_*" }

[feature.mpi.target.osx-arm64.dependencies]
mpich = ">=5.0.0,<6"
fftw = { build = "mpi_*" }

[environments]
mpi5 = ["mpi"]
mpis = ["mpi-slurm"]

[target.osx-arm64.dependencies]
khronos-opencl-icd-loader = ">=2024.10.24,<2025"
ocl_icd_wrapper_apple = ">=1.0.0,<2"

[target.linux-64.dependencies]
cuda-compiler = ">=12.4,<14"
cuda-libraries = ">=12.4,<14"
cuda-libraries-dev = ">=12.4,<14"
cuda-nvml-dev = ">=12.4,<14"
ocl-icd = ">=2.3.4,<3"
