[workspace]
authors = ["HU Xuesong <87519979+huxs001@users.noreply.github.com>"]
channels = ["conda-forge", "bioconda"]
name = "boltz"
platforms = ["linux-64"]
version = "0.1.0"

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu128"]

[system-requirements]
cuda = "12"

[activation.env]
BOLTZ_CACHE = "$PIXI_PROJECT_ROOT/boltz_cache"
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"

[tasks]
ins = 'pip install pytorch-lightning==2.5.0.post0'
test = "boltz predict ligand.yaml --out_dir test --override --use_potentials"
_mkdir = "mkdir -p $BOLTZ_CACHE"

[tasks._fetch]
depends-on = [ "_mkdir" ]
args = [
	"repo",
	"file",
	{ "arg" = "outdir", "default" = "boltz_cache" },
	{ "arg" = "endpoint", "default" = "https://hf-mirror.com" },
]
cmd = "wget -c -P {{outdir}} {{endpoint}}/{{repo}}/resolve/main/{{file}}"
outputs = [ "{{outdir}}/{{file}}" ]

[tasks.fetch]
depends-on = [
	{ task = "_fetch", args = ["boltz-community/boltz-1", "ccd.pkl"] },
	{ task = "_fetch", args = ["boltz-community/boltz-1", "boltz1_conf.ckpt"] },
	{ task = "_fetch", args = ["boltz-community/boltz-2", "mols.tar"] },
	{ task = "_fetch", args = ["boltz-community/boltz-2", "boltz2_conf.ckpt"] },
	{ task = "_fetch", args = ["boltz-community/boltz-2", "boltz2_aff.ckpt"] },
]
cmd = "ls -l $BOLTZ_CACHE/"

[dependencies]
biopython = "1.84.*"
pip = ">=26.0.1,<27"
#c-compiler = ">=1.11.0,<2"
#cxx-compiler = ">=1.11.0,<2"
#cmake = ">=4.3.1,<5"
#ninja = ">=1.13.2,<2"
#pkg-config = ">=0.29.2,<0.30"
zlib = ">=1.3.2,<2"
numpy = "1.26.4.*"
openblas = ">=0.3.32,<0.4"
hydra-core = "1.3.2.*"
pandas = ">=2.2.2"
einops = "0.8.0.*"
einx = "0.3.0.*"
mashumaro = "3.14.*"
modelcif = "1.2.*"
wandb = "0.18.7.*"
click = "8.1.7.*"
pyyaml = "6.0.2.*"
scipy = "1.13.1.*"
numba = "0.61.0.*"
gemmi = "0.6.5.*"
scikit-learn = "1.6.1.*"
chembl_structure_pipeline = "1.2.2.*"
dm-tree = "0.1.8.*"
requests = "2.32.3.*"
types-requests = ">=2.33.0.20260327,<3"
tensorboard = ">=2.20.0,<3"
libstdcxx-ng = ">=15.2.0,<16"
#cuda-compiler = ">=12.9.1,<13"
#cuda-cudart-dev = ">=12.9.79,<13"

[pypi-dependencies]
torch = ">=2.6.0,<3"
pytorch-lightning = "==2.5.0"
boltz = ">=2.2.1, <3"
cuequivariance-ops-cu12 = ">=0.5.0"
cuequivariance-ops-torch-cu12 = ">=0.5.0"
cuequivariance_torch = ">=0.5.0"
