[workspace]
authors = ["HU Xuesong <87519979+huxs001@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "qbics"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
compilers = "*"
blas-devel = "*"
pkgconfig = "*"
cmake = "*"
boost-cpp = ">=1.78"
eigen = ">=3.4.0,<6"
fftw = ">=3.3.10,<4"
hdf5 = ">=1.14.6,<3"
libxc = ">=6.2.2,<8"
plumed = ">=2.9.2,<3"
xtb = ">=6.5.0,<6.6"

[target.linux-64.dependencies]
libblas = { version = "*", build = "*mkl" }
cuda-nvcc = "<12.5"
cuda-cudart-dev = "<12.5"
cuda-libraries-dev = "<12.5"

[target.osx-arm64.dependencies]
libblas = { version = "*", build = "*accelerate" }
