[workspace]
authors = ["HU Xuesong <87519979+huxs001@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "qbics"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[tasks._mkdir]
args = ["dir"]
cmd = "mkdir -p {{dir}}"

[tasks._tarx]
args = ["archive", "dir"]
cmd = "tar -C {{dir}} -xf {{archive}}"

[tasks._patch]
args = [
	"patchfile",
	{ "arg" = "dir", "default" = "." },
	{ "arg" = "strip", "default" = "0" },
]
cmd = "patch -f --posix -r /dev/null -d {{dir}} -p{{strip}} < {{patchfile}}"

[tasks._init_dftd3]
depends-on = [
	{ task = "_mkdir", args = ["third-party/dftd3-0.9"] },
	{ task = "_tarx", args = ["pkg/dftd3-0.9-src.tar.gz", "third-party"] },
	{ task = "_patch", args = ["pkg/dftd3_fixed-a-mistake-in-the-r2r4-for-Barium.patch", "third-party/dftd3-0.9-src", "2"] },
]
cmd = "cd third-party/dftd3-0.9-src; make -j FC=gfortran; cp libdftd3.a dftd3_api.mod ../dftd3-0.9"
outputs = [ "third-party/dftd3-0.9/dftd3_api.mod", "third-party/dftd3-0.9/libdftd3.a" ]

[tasks._init_dlf]
depends-on = [
	{ task = "_mkdir", args = ["third-party"] },
	{ task = "_tarx", args = ["pkg/dl-find-src.tar.gz", "third-party"] },
	{ task = "_patch", args = ["pkg/dlf_allow-arg-mismatch.patch", "third-party/dl-find-src"] },
]
cmd = "cd third-party/dl-find-src; make -f Makefile.qbics"
outputs = [ "third-party/dl-find/libdlf.a" ]

[tasks._fetch]
cmd = "curl -ORC - https://qbics.info/exe/qbics-source.tar.gz"
outputs = ["qbics-source.tar.gz"]

[tasks.init]
depends-on = [ "_init_dftd3", "_init_dlf","_fetch" ]
cmd = "tar -xf qbics-source.tar.gz"
outputs = [ "qbics-source/bin/tools/plotspec.py" ]

[dependencies]
compilers = "*"
blas-devel = "*"
pkg-config = "*"
cmake = "*"
boost-cpp = ">=1.78"
eigen = ">=3.4.0,<6"
fftw = ">=3.3.10,<4"
hdf5 = ">=1.14.6,<3"
libxc = ">=6.2.2,<7"
plumed = ">=2.9.2,<3"
xtb = ">=6.5.0,<6.6"

[feature.openblas.dependencies]
libblas = { version = "*", build = "*openblas" }
openblas = ">=0.3.28,<0.4"

[feature.vendor.target.linux-64.dependencies]
libblas = { version = "*", build = "*mkl" }

[feature.vendor.target.osx-arm64.dependencies]
libblas = { version = "*", build = "*accelerate" }

[environments]
default = ["openblas"]
cpu-open = ["openblas"]
cpu-vendor = ["vendor"]
mpi = ["mpi-compiler"]
cuda = ["cuda-compiler"]

[feature.mpi-compiler.dependencies]
openmpi = ">=4.1.6,<5"
openmpi-mpicc = "*"
openmpi-mpicxx = "*"
openmpi-mpifort = "*"

[feature.mpi-compiler.target.linux-64.dependencies]
fftw = { version = ">=3.3.10,<4", build = "mpi_openmpi_*" }
#hdf5 = { version = ">=1.14.6,<3", build = "mpi_openmpi_*" }
#plumed = { version = ">=2.9.2,<3", build = "mpi_openmpi_*" }

[feature.cuda-compiler]
platforms = ["linux-64"]

[feature.cuda-compiler.dependencies]
libxc = { version = ">=6.2.2,<7", build = "cuda_*" }
cuda-version = "==12.4"
cuda-nvcc = "*"
cuda-cudart-dev = "*"
cuda-libraries-dev = "*"
